-- 采购计划提交表：组员提交采购计划，组长可查看全组数据，组员只看自己的
CREATE TABLE IF NOT EXISTS purchase_plan_submit (
    id                  VARCHAR(32) PRIMARY KEY COMMENT '主键UUID',
    sku                 VARCHAR(200) NOT NULL COMMENT 'SKU',
    wid                 INT NOT NULL COMMENT '仓库ID',
    warehouse_name      VARCHAR(200) COMMENT '仓库名称',
    quantity_plan       INT NOT NULL COMMENT '计划采购量',
    quantity_replenish  INT DEFAULT 0 COMMENT '预估补货量',
    remark              VARCHAR(500) COMMENT '备注（等级|销量|利润）',
    expect_arrive_time  VARCHAR(50) COMMENT '期望到货时间',
    sid                 VARCHAR(100) COMMENT '店铺ID',
    supplier_id         INT COMMENT '供应商ID',
    fnsku               VARCHAR(100) COMMENT 'FNSKU',
    purchaser_id        INT COMMENT '采购方ID',
    plan_sn             VARCHAR(100) COMMENT '领星返回的采购计划单号',
    ppg_sn              VARCHAR(100) COMMENT '领星返回的批次号',
    status_text         VARCHAR(50) DEFAULT '已提交' COMMENT '状态',
    creator_owner_name  VARCHAR(100) NOT NULL COMMENT '创建人（负责人名称）',
    creator_account     VARCHAR(100) NOT NULL COMMENT '创建人账号',
    creator_role        VARCHAR(20) NOT NULL DEFAULT 'user' COMMENT '创建人角色',
    submit_time         DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '提交时间',
    create_time         DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_time         DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_owner (creator_owner_name),
    INDEX idx_account (creator_account),
    INDEX idx_submit_time (submit_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='采购计划提交记录';
