CREATE TABLE IF NOT EXISTS inventory_overview (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    warehouse_names VARCHAR(50) NOT NULL COMMENT 'site',
    sku VARCHAR(200) NOT NULL COMMENT 'SKU',
    product_name VARCHAR(500) DEFAULT '' COMMENT 'product name',
    sku_level VARCHAR(5) DEFAULT 'E' COMMENT 'SKU level',
    last30_days_profit DECIMAL(10,2) DEFAULT NULL,
    return_rate DECIMAL(10,4) DEFAULT NULL,
    overseas_onway INT DEFAULT 0,
    overseas_sellable INT DEFAULT 0,
    overseas_total INT DEFAULT 0,
    purchase_pending_delivery INT DEFAULT 0,
    local_sellable INT DEFAULT 0,
    local_onway INT DEFAULT 0,
    purchase_plan VARCHAR(20) DEFAULT '0',
    lock_num INT DEFAULT 0,
    total_inventory INT DEFAULT 0,
    last7_days_sales INT DEFAULT 0,
    last30_days_sales INT DEFAULT 0,
    last90_days_sales INT DEFAULT 0,
    max_monthly_sales INT DEFAULT NULL,
    overseas_in_stock_ratio DECIMAL(10,1) DEFAULT NULL,
    overseas_total_ratio DECIMAL(10,1) DEFAULT NULL,
    total_inventory_ratio DECIMAL(10,1) DEFAULT NULL,
    last_local_outbound_time VARCHAR(20) DEFAULT '',
    outbound_days INT DEFAULT NULL,
    purchase_cycle INT DEFAULT NULL,
    purchase_quantity DECIMAL(10,0) DEFAULT NULL,
    max_monthly_replenish INT DEFAULT NULL,
    owner VARCHAR(100) DEFAULT '',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_site_sku (warehouse_names, sku),
    INDEX idx_owner (owner)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
