ALTER TABLE inventory_overview MODIFY COLUMN warehouse_names VARCHAR(50) NOT NULL COMMENT '站点';
ALTER TABLE inventory_overview MODIFY COLUMN sku VARCHAR(200) NOT NULL COMMENT 'SKU';
ALTER TABLE inventory_overview MODIFY COLUMN product_name VARCHAR(500) DEFAULT '' COMMENT '产品名称';
ALTER TABLE inventory_overview MODIFY COLUMN sku_level VARCHAR(5) DEFAULT 'E' COMMENT 'SKU等级';
ALTER TABLE inventory_overview MODIFY COLUMN last30_days_profit DECIMAL(10,2) COMMENT '近30利润';
ALTER TABLE inventory_overview MODIFY COLUMN return_rate DECIMAL(10,4) COMMENT '退货率';
ALTER TABLE inventory_overview MODIFY COLUMN overseas_onway INT DEFAULT 0 COMMENT '海外在途';
ALTER TABLE inventory_overview MODIFY COLUMN overseas_sellable INT DEFAULT 0 COMMENT '海外可售';
ALTER TABLE inventory_overview MODIFY COLUMN overseas_total INT DEFAULT 0 COMMENT '海外总库存';
ALTER TABLE inventory_overview MODIFY COLUMN purchase_pending_delivery INT DEFAULT 0 COMMENT '采购待交付';
ALTER TABLE inventory_overview MODIFY COLUMN local_sellable INT DEFAULT 0 COMMENT '成都可售';
ALTER TABLE inventory_overview MODIFY COLUMN local_onway INT DEFAULT 0 COMMENT '成都在途';
ALTER TABLE inventory_overview MODIFY COLUMN purchase_plan VARCHAR(20) DEFAULT '0' COMMENT '采购计划';
ALTER TABLE inventory_overview MODIFY COLUMN lock_num INT DEFAULT 0 COMMENT '待出库';
ALTER TABLE inventory_overview MODIFY COLUMN total_inventory INT DEFAULT 0 COMMENT '总库存';
ALTER TABLE inventory_overview MODIFY COLUMN last7_days_sales INT DEFAULT 0 COMMENT '近7天销量';
ALTER TABLE inventory_overview MODIFY COLUMN last30_days_sales INT DEFAULT 0 COMMENT '近30天销量';
ALTER TABLE inventory_overview MODIFY COLUMN last90_days_sales INT DEFAULT 0 COMMENT '近3月销量';
ALTER TABLE inventory_overview MODIFY COLUMN max_monthly_sales INT COMMENT '历史最大月销';
ALTER TABLE inventory_overview MODIFY COLUMN overseas_in_stock_ratio DECIMAL(10,1) COMMENT '海外在库库销比';
ALTER TABLE inventory_overview MODIFY COLUMN overseas_total_ratio DECIMAL(10,1) COMMENT '海外总库销比';
ALTER TABLE inventory_overview MODIFY COLUMN total_inventory_ratio DECIMAL(10,1) COMMENT '总库存库销比';
ALTER TABLE inventory_overview MODIFY COLUMN last_local_outbound_time VARCHAR(20) DEFAULT '' COMMENT '最近成都出库';
ALTER TABLE inventory_overview MODIFY COLUMN outbound_days INT COMMENT '出库天数';
ALTER TABLE inventory_overview MODIFY COLUMN purchase_cycle INT COMMENT '采购周期';
ALTER TABLE inventory_overview MODIFY COLUMN purchase_quantity DECIMAL(10,0) COMMENT '采购数量';
ALTER TABLE inventory_overview MODIFY COLUMN max_monthly_replenish INT COMMENT '最大月销补货量';
ALTER TABLE inventory_overview MODIFY COLUMN owner VARCHAR(100) DEFAULT '' COMMENT '负责人';
ALTER TABLE inventory_overview MODIFY COLUMN updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE inventory_overview COMMENT = '库存总览预计算表';
