DROP TABLE IF EXISTS purchase_plan;
CREATE TABLE purchase_plan (
    id VARCHAR(32) NOT NULL COMMENT 'UUID',
    plan_sn VARCHAR(50) DEFAULT '' COMMENT '采购计划编号',
    ppg_sn VARCHAR(50) DEFAULT '' COMMENT '采购计划批次号',
    product_name VARCHAR(200) DEFAULT '' COMMENT '品名',
    sku VARCHAR(200) DEFAULT '' COMMENT 'SKU',
    fnsku VARCHAR(100) DEFAULT '' COMMENT 'FNSKU',
    pic_url VARCHAR(500) DEFAULT '' COMMENT '产品图片',
    supplier_id VARCHAR(50) DEFAULT '' COMMENT '供应商id',
    supplier_name VARCHAR(200) DEFAULT '' COMMENT '供应商名称',
    status_text VARCHAR(20) DEFAULT '' COMMENT '状态说明',
    status INT DEFAULT 0 COMMENT '状态值: 2待采购 -2已完成 121待审批 122已驳回 -3/124已作废',
    sid VARCHAR(50) DEFAULT '' COMMENT '店铺id',
    seller_name VARCHAR(200) DEFAULT '' COMMENT '店铺名称',
    marketplace VARCHAR(50) DEFAULT '' COMMENT '国家',
    expect_arrive_time VARCHAR(20) DEFAULT '' COMMENT '期望到货时间',
    remark VARCHAR(500) DEFAULT '' COMMENT '产品备注',
    quantity_plan INT DEFAULT 0 COMMENT '计划采购量',
    product_id INT DEFAULT 0 COMMENT '商品id',
    cg_uid INT DEFAULT 0 COMMENT '采购员id',
    cg_opt_username VARCHAR(50) DEFAULT '' COMMENT '采购员名称',
    cg_box_pcs INT DEFAULT 0 COMMENT '单箱数量',
    is_combo INT DEFAULT 0 COMMENT '组合商品: 0否 1是',
    is_aux INT DEFAULT 0 COMMENT '辅料: 0否 1是',
    is_related_process_plan INT DEFAULT 0 COMMENT '关联加工计划: 0否 1是',
    spu VARCHAR(100) DEFAULT '' COMMENT 'SPU',
    spu_name VARCHAR(200) DEFAULT '' COMMENT '款名',
    creator_uid INT DEFAULT 0 COMMENT '创建人id',
    creator_real_name VARCHAR(50) DEFAULT '' COMMENT '创建人名称',
    wid INT DEFAULT 0 COMMENT '仓库id',
    warehouse_name VARCHAR(100) DEFAULT '' COMMENT '仓库名称',
    purchaser_id INT DEFAULT 0 COMMENT '采购方id',
    purchaser_name VARCHAR(200) DEFAULT '' COMMENT '采购方名称',
    create_time VARCHAR(30) DEFAULT '' COMMENT '创建时间',
    plan_remark VARCHAR(500) DEFAULT '' COMMENT '计划备注',
    attribute_json JSON COMMENT '属性',
    file_json JSON COMMENT '附件',
    msku_json JSON COMMENT 'MSKU',
    perm_uid_json JSON COMMENT '单据负责人uid',
    perm_username_json JSON COMMENT '单据负责人名称',
    upload_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_plan_sku (plan_sn, sku),
    KEY idx_ppg_sn (ppg_sn),
    KEY idx_sku (sku),
    KEY idx_status (status),
    KEY idx_create_time (create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='采购计划(全字段)';
